export enum BATTLE_BACKGROUND_ASSET_KEYS {
    FOREST = "FOREST",
}

export enum MONSTER_ASSET_KEYS {
    IGUANIGNITE = "IGUANIGNITE",
    CARNODUSK = "CARNODUSK",
}

export enum BATTLE_ASSET_KEYS {
    HEALTH_BAR_BACKGROUND = "HEALTH_BAR_ASSET_KEYS",
}

export enum HEALTH_BAR_ASSET_KEYS {
    LEFT_CAP = "LEFT_CAP",
    RIGHT_CAP = "RIGHT_CAP",
    MIDDLE = "MIDDLE",
}
